# Welcome to Jekyll!
#
# Site settings
title: Prajyukttam
description: |
  Explore. Innovate. Inspire.

owner: Avi # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: prajyukttam@dbuniversity.ac.in
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://prajyukttam.com" # the base hostname & protocol for your site
social:
  facebook-official: https://facebook.com/prajyukttam
  instagram: https://instagram.com/prajyukttam
  email: mailto:prajyukttam@dbuniversity.ac.in

# Build settings
markdown: kramdown
